# Generated by Django 5.2.5 on 2025-08-17 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='national_id',
        ),
    ]
