# Generated by Django 5.2.5 on 2025-08-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is read?')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Is replied?')),
            ],
            options={
                'verbose_name': 'Contactus',
                'verbose_name_plural': 'Contactus',
            },
        ),
    ]
